[package]
name    = "cuckoo-bench"
version = "0.0.0"
authors = ["Casey Rodarmor <casey.rodarmor@layer1.capital>"]
edition = "2018"

[dependencies]
structopt    = "0.2.13"
serde_yaml   = "0.8.8"
serde        = "1.0.81"
serde_derive = "1.0.81"

[dependencies.git]
package = "git2"
version = "0.7.5"
